export const FdData = [
  {
    bank: 'Bandhan Bank',
    rate: 8.0,
    tenor: '600 days',
    senior: 8.5,
  },
  {
    bank: 'Tamilnad Mercantile Bank',
    rate: 8.0,
    tenor: '300 days',
    senior: 8.5,
  },
  {
    bank: 'DCB Bank',
    rate: 7.85,
    tenor: '15 to < 18 months',
    senior: 8.5,
  },
  {
    bank: 'RBL Bank',
    rate: 7.8,
    tenor: '453 to 725 days',
    senior: 8.3,
  },
  {
    bank: 'YES Bank',
    rate: 7.75,
    tenor: '35 months',
    senior: 8.25,
  },
  {
    bank: 'City Union Bank',
    rate: 7.75,
    tenor: '444 days',
    senior: 8.0,
  },
  {
    bank: 'IDFC First Bank',
    rate: 7.5,
    tenor: '> 18 months to 3 years',
    senior: 8.0,
  },
  {
    bank: 'Catholic Syrian Bank',
    rate: 7.5,
    tenor: '750 days',
    senior: 7.5,
  },
  {
    bank: 'Induslnd Bank',
    rate: 7.5,
    tenor: '24 to 39 months',
    senior: 8.25,
  },
  {
    bank: 'Karur Vysya Bank',
    rate: 7.5,
    tenor: '444 days',
    senior: 8.0,
  },
  {
    bank: 'South Indian Bank',
    rate: 7.4,
    tenor: '500 days',
    senior: 7.4,
  },
  {
    bank: 'Karnataka Bank',
    rate: 7.3,
    tenor: '555 days',
    senior: 7.7,
  },

  {
    bank: 'Axis Bank',
    rate: 7.26,
    tenor: '24 to > 30 months',
    senior: 8.01,
  },
  {
    bank: 'Federal Bank',
    rate: 7.25,
    tenor: '15 to 24 months',
    senior: 7.75,
  },
  {
    bank: 'TNSC Bank',
    rate: 7.25,
    tenor: '600 days',
    senior: 7.75,
  },
  {
    bank: 'Dhanlaxmi Bank',
    rate: 7.25,
    tenor: '555 days',
    senior: 7.75,
  },
  {
    bank: 'J & K Bank',
    rate: 7.25,
    tenor: '12 to < 24 months',
    senior: 7.75,
  },
  {
    bank: 'Kotak Mahindra Bank',
    rate: 7.2,
    tenor: '390 days to < 24 months',
    senior: 7.7,
  },
  {
    bank: 'Nainital Bank',
    rate: 7.1,
    tenor: '705 days',
    senior: 7.6,
  },
  {
    bank: 'HDFC Bank',
    rate: 7.1,
    tenor: '15 to < 18 months',
    senior: 7.6,
  },
  {
    bank: 'ICICI Bank',
    rate: 7.0,
    tenor: '15 to 60 months',
    senior: 7.5,
  },
]
